#!/usr/bin/env bash
DEBIAN_FRONTEND=noninteractive

APT_PACKAGES="
  autotools-dev
  automake
  bison
  build-essential
  curl
  editorconfig
  flex
  gettext
  git
  iputils-ping
  libbz2-dev
  libevent-dev
  libffi-dev
  liblzma-dev
  libncurses5-dev
  libncursesw5-dev
  libprotobuf-dev
  libreadline-dev
  libssl-dev
  libsqlite3-dev
  llvm
  net-tools
  netcat-openbsd
  pkg-config
  protobuf-compiler
  python-openssl
  rsync
  ruby
  ruby-dev
  silversearcher-ag
  socat
  software-properties-common
  tk-dev
  tree
  vim
  wget
  xz-utils
  yadm
  zlib1g-dev
  zsh
"

NODEJS_PACKAGES="
  eslint
  stylelint
  typescript
  @vue/cli
"

PYTHON_PACKAGES="
  autopep8
  cookiecutter
  flake8
  isort
  pylint
  yapf
"

# system packages
echo "** Installing system packages..."
TOINSTALL=
for package in ${APT_PACKAGES} ; do
  if ! dpkg -s $package >/dev/null 2>&1; then
    TOINSTALL="${package} ${TOINSTALL} "
  fi
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  sudo apt install -y ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

# update yadm's remote origin to use git instead of https
yadm remote set-url origin "git@github.com:akngs/dotfiles.git"

# zsh
if [[ "/usr/bin/zsh" != "$SHELL" ]] ; then
  echo "** Changing shell to zsh"
  chsh -s /usr/bin/zsh
fi

# oh-my-zsh
if [[ ! -d ~/.oh-my-zsh ]] ; then
  echo "** Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# mosh
if [[ ! -x /usr/local/bin/mosh ]] ; then
  echo "** Installing mosh"
  git clone https://github.com/mobile-shell/mosh
  cd mosh
  ./autogen.sh
  ./configure
  make
  sudo make install
  cd ..
  rm -rf mosh
fi

# vim-plug
if [[ ! -f ~/.vim/autoload/plug.vim ]] ; then
  echo "** Installing vim-plug"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# tmux
if [[ ! -x /usr/local/bin/tmux ]] ; then
  echo "** Installing tmux"
  git clone https://github.com/tmux/tmux.git
  cd tmux
  sh autogen.sh
  ./configure
  make
  sudo make install
  cd ..
  rm -rf tmux
fi

# jekyll
if [[ ! -x /usr/local/bin/jekyll ]] ; then
  echo "** Installing jekyll"
  sudo gem install bundle jekyll
fi

# fzf
if [[ ! -d ~/.fzf ]] ; then
  echo "** Installing fzf"
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all
  rm -f ~/.fzf.bash
  rm -f ~/.fzf.fish
  sudo ln -sf ~/.fzf/bin/fzf /usr/local/bin/fzf
fi

# nodejs
if [[ ! -f /usr/bin/nodejs ]] ; then
  echo "** Installing nodejs"
  curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  sudo apt install -y nodejs
fi

# pyenv
if [[ ! -d ~/.pyenv ]] ; then
  echo "** Installing pyenv and python"
  curl https://pyenv.run | bash
  ~/.pyenv/bin/pyenv install 3.7.4
  ~/.pyenv/bin/pyenv global 3.7.4
  pip install --upgrade pip
fi

# poetry
if [[ ! -d ~/.poetry ]] ; then
  echo "** Installing poetry"
  curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  mkdir -p ~/.oh-my-zsh/plugins/poetry
  ~/.poetry/bin/poetry completions zsh > ~/.oh-my-zsh/plugins/poetry/_poetry
fi

# nodejs packages
echo "** Installing nodejs packages..."
TOINSTALL=
for package in ${NODEJS_PACKAGES} ; do
  sudo npm list -g ${package} >/dev/null 2>&1 || TOINSTALL="${package} ${TOINSTALL} "
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  sudo npm install -g ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

# python packages
echo "** Installing python packages..."
TOINSTALL=
for package in ${PYTHON_PACKAGES} ; do
  pip list | grep ${package} >/dev/null 2>&1 || TOINSTALL="${package} ${TOINSTALL} "
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  pip install ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

