#!/usr/bin/env bash
DEBIAN_FRONTEND=noninteractive

APT_PACKAGES="
  autotools-dev
  automake
  bison
  build-essential
  curl
  editorconfig
  flex
  gettext
  git
  iputils-ping
  libbz2-dev
  libevent-dev
  libffi-dev
  liblzma-dev
  libncurses5-dev
  libncursesw5-dev
  libprotobuf-dev
  libreadline-dev
  libssl-dev
  libsqlite3-dev
  llvm
  mosh
  net-tools
  netcat-openbsd
  pkg-config
  protobuf-compiler
  python-openssl
  rsync
  ruby
  ruby-dev
  silversearcher-ag
  socat
  software-properties-common
  tk-dev
  tmux
  tmuxinator
  tree
  vim
  wget
  xz-utils
  yadm
  zlib1g-dev
  zsh
"

NODEJS_PACKAGES="
  eslint
  stylelint
  typescript
  @vue/cli
"

PYTHON_PACKAGES="
  autopep8
  cookiecutter
  flake8
  isort
  pylint
  yapf
"

# Install system packages
echo "** Installing system packages..."
TOINSTALL=
for package in ${APT_PACKAGES} ; do
  if ! dpkg -s $package >/dev/null 2>&1; then
    TOINSTALL="${package} ${TOINSTALL} "
  fi
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  sudo apt install -y ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

# Update yadm's remote origin to use git instead of https
yadm remote set-url origin "git@github.com:akngs/dotfiles.git"

# Change shell to zsh
if [[ "/usr/bin/zsh" != "$SHELL" ]] ; then
   echo "** Changing shell to zsh"
  chsh -s /usr/bin/zsh
fi

# Install oh-my-zsh
if [[ ! -d ~/.oh-my-zsh ]] ; then
  echo "** Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Install nodejs
if [[ ! -f /usr/bin/nodejs ]] ; then
  echo "** Installing nodejs"
  curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  sudo apt install -y nodejs
fi

# Install pyenv
if [[ ! -d ~/.pyenv ]] ; then
  echo "** Installing pyenv and python"
  curl https://pyenv.run | bash
  ~/.pyenv/bin/pyenv install 3.7.4
  ~/.pyenv/bin/pyenv global 3.7.4
  pip install --upgrade pip
fi

# Install poetry
if [[ ! -d ~/.poetry ]] ; then
  echo "** Installing poetry"
  curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  mkdir -p ~/.oh-my-zsh/plugins/poetry
  ~/.poetry/bin/poetry completions zsh > ~/.oh-my-zsh/plugins/poetry/_poetry
fi

# Install jekyll
if [[ ! -x /usr/local/bin/jekyll ]] ; then
  echo "** Installing jekyll"
  sudo gem install bundle jekyll
fi

# Install nodejs packages
echo "** Installing nodejs packages..."
TOINSTALL=
for package in ${NODEJS_PACKAGES} ; do
  sudo npm list -g ${package} >/dev/null 2>&1 || TOINSTALL="${package} ${TOINSTALL} "
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  sudo npm install -g ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

# Install python packages
echo "** Installing python packages..."
TOINSTALL=
for package in ${PYTHON_PACKAGES} ; do
  pip list | grep ${package} >/dev/null 2>&1 || TOINSTALL="${package} ${TOINSTALL} "
done
if [[ "" != "${TOINSTALL}" ]] ; then
  echo "   (packages to install: ${TOINSTALL})"
  pip install ${TOINSTALL}
else
  echo "   (nothing to install)"
fi

